name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip
  - matplotlib==3.8.4
  - numpy==1.26.4
  - pandas==2.0.3
  - scikit-learn==1.3.2
  - pytorch==1.13.0
  - jieba==0.42.1
  - gensim==4.3.3
  - tqdm==4.66.1
